export const ADMIN_PATHS = {
  login: '/admin/login',
  recuperar: '/admin/recuperar',
  dashboard: '/admin/dashboard',
  atractivos: '/admin/atractivos',
  atractivosNuevo: '/admin/atractivos/nuevo',
  atractivoEditar: (id) => `/admin/atractivos/${id}/editar`,
  rutas: '/admin/rutas',
  rutasNueva: '/admin/rutas/nueva',
  rutaEditar: (id) => `/admin/rutas/${id}/editar`,
  emprendimientos: '/admin/emprendimientos',
  emprendimientosNuevo: '/admin/emprendimientos/nuevo',
  emprendimientoEditar: (id) => `/admin/emprendimientos/${id}/editar`,
  eventos: '/admin/eventos',
  eventosNuevo: '/admin/eventos/nuevo',
  eventoEditar: (id) => `/admin/eventos/${id}/editar`,
  catalogos: '/admin/catalogos',
  usuarios: '/admin/usuarios',
  usuariosNuevo: '/admin/usuarios/nuevo',
  usuarioEditar: (id) => `/admin/usuarios/${id}/editar`,
  configuracion: '/admin/configuracion',
  auditoria: '/admin/auditoria',
  reportes: '/admin/reportes',
  sinPermiso: '/admin/sin-permiso',
  perfil: '/admin/perfil',
};
