# Generated by Django 6.0.5 on 2026-05-28 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atractivos', '0001_initial'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duracion_estimada', models.CharField(blank=True, max_length=100, null=True)),
                ('dificultad', models.CharField(blank=True, max_length=50, null=True)),
                ('punto_inicio', models.CharField(blank=True, max_length=255, null=True)),
                ('punto_fin', models.CharField(blank=True, max_length=255, null=True)),
                ('lat_inicio', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('lon_inicio', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('lat_fin', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('lon_fin', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('geojson_ruta', models.JSONField(blank=True, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('visitas', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='catalogos.estadopublicacion')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='catalogos.parroquia')),
            ],
            options={
                'verbose_name': 'Ruta',
                'db_table': 'rutas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RutaAtractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_recorrido', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('atractivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='atractivos.atractivo')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atractivos', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Atracción de Ruta',
                'db_table': 'ruta_atractivos',
                'ordering': ['orden_recorrido'],
                'unique_together': {('ruta', 'atractivo')},
            },
        ),
    ]
