from django.urls import path

from .views import (
    api_root,
    atractivos_list,
    atractivos_detail,
    admin_atractivos_list,
    admin_atractivo_delete,
    admin_atractivo_cambiar_estado,
    admin_atractivo_form_data,
    admin_atractivo_get_for_edit,
    admin_atractivo_save,
    catalogo_categoria_create,
    catalogo_parroquia_create,
    rutas_list,
    rutas_detail,
    emprendimientos_list,
    emprendimientos_detail,
    usuarios_list,
    eventos_list,
    publicaciones_list,
    reportes_list,
    auditorias_list,
    dashboard_summary,
    configuracion_list,
)
from .auth_views import register, login, password_reset_request, password_reset_confirm
from .admin.rutas_views import (
    admin_rutas_list,
    admin_ruta_delete,
    admin_ruta_cambiar_estado,
    admin_ruta_form_data,
    admin_ruta_get_for_edit,
    admin_ruta_save,
)
from .admin.multimedia_views import (
    multimedia_list,
    multimedia_upload,
    multimedia_set_principal,
    multimedia_delete,
    multimedia_reorder,
)
from .admin.emprendimientos_views import (
    admin_emprendimientos_list,
    admin_emprendimiento_delete,
    admin_emprendimiento_cambiar_estado,
    admin_emprendimiento_form_data,
    admin_emprendimiento_get_for_edit,
    admin_emprendimiento_save,
)

urlpatterns = [
    path('api/', api_root, name='api-root'),
    path('api/atractivos/', atractivos_list, name='api-atractivos'),
    path('api/atractivos/<slug:slug>/', atractivos_detail, name='api-atractivos-detail'),
    path('api/admin/atractivos/', admin_atractivos_list, name='api-admin-atractivos'),
    path('api/admin/atractivos/form-data/', admin_atractivo_form_data, name='api-admin-atractivo-form-data'),
    path('api/admin/atractivos/new/', admin_atractivo_save, name='api-admin-atractivo-create'),
    path('api/admin/atractivos/<int:atractivo_id>/', admin_atractivo_delete, name='api-admin-atractivo-delete'),
    path('api/admin/atractivos/<int:atractivo_id>/form-data/', admin_atractivo_get_for_edit, name='api-admin-atractivo-form-data-edit'),
    path('api/admin/atractivos/<int:atractivo_id>/edit/', admin_atractivo_save, name='api-admin-atractivo-edit'),
    path('api/admin/atractivos/<int:atractivo_id>/cambiar-estado/', admin_atractivo_cambiar_estado, name='api-admin-atractivo-cambiar-estado'),
    path('api/catalogos/categorias/', catalogo_categoria_create, name='api-catalogo-categoria-create'),
    path('api/catalogos/parroquias/', catalogo_parroquia_create, name='api-catalogo-parroquia-create'),
    path('api/admin/rutas/', admin_rutas_list, name='api-admin-rutas'),
    path('api/admin/rutas/form-data/', admin_ruta_form_data, name='api-admin-ruta-form-data'),
    path('api/admin/rutas/new/', admin_ruta_save, name='api-admin-ruta-create'),
    path('api/admin/rutas/<int:ruta_id>/', admin_ruta_delete, name='api-admin-ruta-delete'),
    path('api/admin/rutas/<int:ruta_id>/form-data/', admin_ruta_get_for_edit, name='api-admin-ruta-form-data-edit'),
    path('api/admin/rutas/<int:ruta_id>/edit/', admin_ruta_save, name='api-admin-ruta-edit'),
    path('api/admin/rutas/<int:ruta_id>/cambiar-estado/', admin_ruta_cambiar_estado, name='api-admin-ruta-cambiar-estado'),
    path('api/admin/emprendimientos/', admin_emprendimientos_list, name='api-admin-emprendimientos'),
    path('api/admin/emprendimientos/form-data/', admin_emprendimiento_form_data, name='api-admin-emprendimiento-form-data'),
    path('api/admin/emprendimientos/new/', admin_emprendimiento_save, name='api-admin-emprendimiento-create'),
    path('api/admin/emprendimientos/<int:emprendimiento_id>/', admin_emprendimiento_delete, name='api-admin-emprendimiento-delete'),
    path('api/admin/emprendimientos/<int:emprendimiento_id>/form-data/', admin_emprendimiento_get_for_edit, name='api-admin-emprendimiento-form-data-edit'),
    path('api/admin/emprendimientos/<int:emprendimiento_id>/edit/', admin_emprendimiento_save, name='api-admin-emprendimiento-edit'),
    path('api/admin/emprendimientos/<int:emprendimiento_id>/cambiar-estado/', admin_emprendimiento_cambiar_estado, name='api-admin-emprendimiento-cambiar-estado'),
    path('api/admin/multimedia/', multimedia_list, name='api-admin-multimedia-list'),
    path('api/admin/multimedia/upload/', multimedia_upload, name='api-admin-multimedia-upload'),
    path('api/admin/multimedia/reorder/', multimedia_reorder, name='api-admin-multimedia-reorder'),
    path('api/admin/multimedia/<int:multimedia_id>/principal/', multimedia_set_principal, name='api-admin-multimedia-principal'),
    path('api/admin/multimedia/<int:multimedia_id>/', multimedia_delete, name='api-admin-multimedia-delete'),
    path('api/rutas/', rutas_list, name='api-rutas'),
    path('api/rutas/<int:ruta_id>/', rutas_detail, name='api-rutas-detail'),
    path('api/emprendimientos/', emprendimientos_list, name='api-emprendimientos'),
    path('api/emprendimientos/<int:emp_id>/', emprendimientos_detail, name='api-emprendimientos-detail'),
    path('api/usuarios/', usuarios_list, name='api-usuarios'),
    path('api/eventos/', eventos_list, name='api-eventos'),
    path('api/publicaciones/', publicaciones_list, name='api-publicaciones'),
    path('api/reportes/', reportes_list, name='api-reportes'),
    path('api/auditorias/', auditorias_list, name='api-auditorias'),
    path('api/dashboard/', dashboard_summary, name='api-dashboard-summary'),
    path('api/configuracion/', configuracion_list, name='api-configuracion'),
    path('api/auth/register/', register, name='api-auth-register'),
    path('api/auth/login/', login, name='api-auth-login'),
    path('api/auth/password-reset/', password_reset_request, name='api-auth-password-reset'),
    path('api/auth/password-reset/confirm/', password_reset_confirm, name='api-auth-password-reset-confirm'),
]
