from django.urls import path

from .views import (
    api_root,
    atractivos_list,
    atractivos_detail,
    galeria_publica_list,
    catalogos_publicos_list,
    admin_atractivos_list,
    admin_atractivo_delete,
    admin_atractivo_cambiar_estado,
    admin_atractivo_form_data,
    admin_atractivo_get_for_edit,
    admin_atractivo_save,
    catalogo_categoria_create,
    catalogo_parroquia_create,
    rutas_list,
    rutas_detail,
    emprendimientos_list,
    emprendimientos_detail,
    usuarios_list,
    eventos_list,
    eventos_detail,
    admin_evento_detail,
    publicaciones_list,
    reportes_list,
    auditorias_list,
    dashboard_summary,
    configuracion_list,
)
from .auth_views import register, login, password_reset_request, password_reset_confirm
from .resenas_views import resenas_list, resenas_create, resenas_update
from .admin.resenas_views import admin_resenas_list, admin_resenas_cambiar_activo
from .admin.rutas_views import (
    admin_rutas_list,
    admin_ruta_delete,
    admin_ruta_cambiar_estado,
    admin_ruta_form_data,
    admin_ruta_get_for_edit,
    admin_ruta_save,
)
from .admin.multimedia_views import (
    multimedia_list,
    multimedia_upload,
    multimedia_set_principal,
    multimedia_delete,
    multimedia_reorder,
)
from .admin.emprendimientos_views import (
    admin_emprendimientos_list,
    admin_emprendimiento_delete,
    admin_emprendimiento_cambiar_estado,
    admin_emprendimiento_form_data,
    admin_emprendimiento_get_for_edit,
    admin_emprendimiento_save,
)
from .admin.eventos_views import (
    admin_eventos_list,
    admin_evento_delete,
    admin_evento_cambiar_estado,
    admin_evento_form_data,
    admin_evento_get_for_edit,
    admin_evento_save,
)
from .admin.catalogos_views import (
    admin_catalogo_list,
    admin_catalogo_get,
    admin_catalogo_save,
    admin_catalogo_cambiar_estado,
)
from .admin.usuarios_views import (
    admin_usuarios_list,
    admin_usuario_form_data,
    admin_usuario_get_for_edit,
    admin_usuario_save,
    admin_usuario_cambiar_estado,
    admin_usuario_delete,
    admin_usuario_foto,
)
from .admin.configuracion_views import (
    admin_configuracion_get,
    admin_configuracion_guardar_gad,
    admin_configuracion_guardar_apariencia,
    admin_configuracion_guardar_redes,
    admin_configuracion_guardar_sobre_pelileo,
    admin_configuracion_guardar_autoridades,
    admin_configuracion_guardar_guias,
    admin_configuracion_guardar_header_footer,
    admin_configuracion_guardar_menu,
    admin_configuracion_guardar_mapa,
    admin_configuracion_subir_imagen,
)
from .admin.reportes_views import (
    admin_reportes_list,
    admin_reportes_filtros,
    admin_reporte_generar,
    admin_reporte_descargar,
)
from .admin.perfil_views import (
    admin_perfil_get,
    admin_perfil_actualizar,
    admin_perfil_cambiar_password,
    admin_perfil_foto,
)
from .admin.ficha_views import (
    admin_atractivo_ficha_descargar,
    admin_ruta_ficha_descargar,
    admin_emprendimiento_ficha_descargar,
    admin_evento_ficha_descargar,
)
from .admin.errores_views import (
    admin_errores_list,
    admin_errores_cambiar_estado,
    admin_errores_reportar_cliente,
)
from .admin.papelera_views import (
    admin_papelera_list,
    admin_papelera_restaurar,
    admin_papelera_eliminar_permanente,
)

urlpatterns = [
    path('api/', api_root, name='api-root'),
    path('api/atractivos/', atractivos_list, name='api-atractivos'),
    path('api/atractivos/<slug:slug>/', atractivos_detail, name='api-atractivos-detail'),
    path('api/galeria/', galeria_publica_list, name='api-galeria'),
    path('api/catalogos/publicos/', catalogos_publicos_list, name='api-catalogos-publicos'),
    path('api/admin/atractivos/', admin_atractivos_list, name='api-admin-atractivos'),
    path('api/admin/atractivos/form-data/', admin_atractivo_form_data, name='api-admin-atractivo-form-data'),
    path('api/admin/atractivos/new/', admin_atractivo_save, name='api-admin-atractivo-create'),
    path('api/admin/atractivos/<int:atractivo_id>/', admin_atractivo_delete, name='api-admin-atractivo-delete'),
    path('api/admin/atractivos/<int:atractivo_id>/form-data/', admin_atractivo_get_for_edit, name='api-admin-atractivo-form-data-edit'),
    path('api/admin/atractivos/<int:atractivo_id>/ficha/descargar/', admin_atractivo_ficha_descargar, name='api-admin-atractivo-ficha'),
    path('api/admin/atractivos/<int:atractivo_id>/edit/', admin_atractivo_save, name='api-admin-atractivo-edit'),
    path('api/admin/atractivos/<int:atractivo_id>/cambiar-estado/', admin_atractivo_cambiar_estado, name='api-admin-atractivo-cambiar-estado'),
    path('api/catalogos/categorias/', catalogo_categoria_create, name='api-catalogo-categoria-create'),
    path('api/catalogos/parroquias/', catalogo_parroquia_create, name='api-catalogo-parroquia-create'),
    path('api/admin/rutas/', admin_rutas_list, name='api-admin-rutas'),
    path('api/admin/rutas/form-data/', admin_ruta_form_data, name='api-admin-ruta-form-data'),
    path('api/admin/rutas/new/', admin_ruta_save, name='api-admin-ruta-create'),
    path('api/admin/rutas/<int:ruta_id>/', admin_ruta_delete, name='api-admin-ruta-delete'),
    path('api/admin/rutas/<int:ruta_id>/form-data/', admin_ruta_get_for_edit, name='api-admin-ruta-form-data-edit'),
    path('api/admin/rutas/<int:ruta_id>/ficha/descargar/', admin_ruta_ficha_descargar, name='api-admin-ruta-ficha'),
    path('api/admin/rutas/<int:ruta_id>/edit/', admin_ruta_save, name='api-admin-ruta-edit'),
    path('api/admin/rutas/<int:ruta_id>/cambiar-estado/', admin_ruta_cambiar_estado, name='api-admin-ruta-cambiar-estado'),
    path('api/admin/emprendimientos/', admin_emprendimientos_list, name='api-admin-emprendimientos'),
    path('api/admin/emprendimientos/form-data/', admin_emprendimiento_form_data, name='api-admin-emprendimiento-form-data'),
    path('api/admin/emprendimientos/new/', admin_emprendimiento_save, name='api-admin-emprendimiento-create'),
    path('api/admin/emprendimientos/<int:emprendimiento_id>/', admin_emprendimiento_delete, name='api-admin-emprendimiento-delete'),
    path('api/admin/emprendimientos/<int:emprendimiento_id>/form-data/', admin_emprendimiento_get_for_edit, name='api-admin-emprendimiento-form-data-edit'),
    path('api/admin/emprendimientos/<int:emprendimiento_id>/ficha/descargar/', admin_emprendimiento_ficha_descargar, name='api-admin-emprendimiento-ficha'),
    path('api/admin/emprendimientos/<int:emprendimiento_id>/edit/', admin_emprendimiento_save, name='api-admin-emprendimiento-edit'),
    path('api/admin/emprendimientos/<int:emprendimiento_id>/cambiar-estado/', admin_emprendimiento_cambiar_estado, name='api-admin-emprendimiento-cambiar-estado'),
    path('api/admin/eventos/', admin_eventos_list, name='api-admin-eventos'),
    path('api/admin/eventos/form-data/', admin_evento_form_data, name='api-admin-evento-form-data'),
    path('api/admin/eventos/new/', admin_evento_save, name='api-admin-evento-create'),
    path('api/admin/eventos/<int:evento_id>/', admin_evento_delete, name='api-admin-evento-delete'),
    path('api/admin/eventos/<int:evento_id>/form-data/', admin_evento_get_for_edit, name='api-admin-evento-form-data-edit'),
    path('api/admin/eventos/<int:evento_id>/edit/', admin_evento_save, name='api-admin-evento-edit'),
    path('api/admin/eventos/<int:evento_id>/cambiar-estado/', admin_evento_cambiar_estado, name='api-admin-evento-cambiar-estado'),
    path('api/admin/eventos/<int:evento_id>/ficha/descargar/', admin_evento_ficha_descargar, name='api-admin-evento-ficha'),
    path('api/admin/catalogos/<str:tipo>/', admin_catalogo_list, name='api-admin-catalogo-list'),
    path('api/admin/catalogos/<str:tipo>/new/', admin_catalogo_save, name='api-admin-catalogo-create'),
    path('api/admin/catalogos/<str:tipo>/<int:item_id>/', admin_catalogo_get, name='api-admin-catalogo-get'),
    path('api/admin/catalogos/<str:tipo>/<int:item_id>/edit/', admin_catalogo_save, name='api-admin-catalogo-edit'),
    path('api/admin/catalogos/<str:tipo>/<int:item_id>/cambiar-estado/', admin_catalogo_cambiar_estado, name='api-admin-catalogo-cambiar-estado'),
    path('api/admin/usuarios/', admin_usuarios_list, name='api-admin-usuarios'),
    path('api/admin/usuarios/form-data/', admin_usuario_form_data, name='api-admin-usuario-form-data'),
    path('api/admin/usuarios/new/', admin_usuario_save, name='api-admin-usuario-create'),
    path('api/admin/usuarios/<int:usuario_id>/form-data/', admin_usuario_get_for_edit, name='api-admin-usuario-form-data-edit'),
    path('api/admin/usuarios/<int:usuario_id>/edit/', admin_usuario_save, name='api-admin-usuario-edit'),
    path('api/admin/usuarios/<int:usuario_id>/cambiar-estado/', admin_usuario_cambiar_estado, name='api-admin-usuario-cambiar-estado'),
    path('api/admin/usuarios/<int:usuario_id>/foto/', admin_usuario_foto, name='api-admin-usuario-foto'),
    path('api/admin/usuarios/<int:usuario_id>/', admin_usuario_delete, name='api-admin-usuario-delete'),
    path('api/admin/configuracion/', admin_configuracion_get, name='api-admin-configuracion-get'),
    path('api/admin/configuracion/gad/', admin_configuracion_guardar_gad, name='api-admin-configuracion-gad'),
    path('api/admin/configuracion/apariencia/', admin_configuracion_guardar_apariencia, name='api-admin-configuracion-apariencia'),
    path('api/admin/configuracion/redes/', admin_configuracion_guardar_redes, name='api-admin-configuracion-redes'),
    path('api/admin/configuracion/sobre-pelileo/', admin_configuracion_guardar_sobre_pelileo, name='api-admin-configuracion-sobre-pelileo'),
    path('api/admin/configuracion/autoridades/', admin_configuracion_guardar_autoridades, name='api-admin-configuracion-autoridades'),
    path('api/admin/configuracion/guias/', admin_configuracion_guardar_guias, name='api-admin-configuracion-guias'),
    path('api/admin/configuracion/header-footer/', admin_configuracion_guardar_header_footer, name='api-admin-configuracion-header-footer'),
    path('api/admin/configuracion/menu/', admin_configuracion_guardar_menu, name='api-admin-configuracion-menu'),
    path('api/admin/configuracion/mapa/', admin_configuracion_guardar_mapa, name='api-admin-configuracion-mapa'),
    path('api/admin/configuracion/imagen/', admin_configuracion_subir_imagen, name='api-admin-configuracion-imagen'),
    path('api/admin/reportes/', admin_reportes_list, name='api-admin-reportes'),
    path('api/admin/reportes/filtros/', admin_reportes_filtros, name='api-admin-reportes-filtros'),
    path('api/admin/reportes/generar/', admin_reporte_generar, name='api-admin-reporte-generar'),
    path('api/admin/reportes/<int:reporte_id>/descargar/', admin_reporte_descargar, name='api-admin-reporte-descargar'),
    path('api/admin/perfil/', admin_perfil_get, name='api-admin-perfil-get'),
    path('api/admin/perfil/actualizar/', admin_perfil_actualizar, name='api-admin-perfil-actualizar'),
    path('api/admin/perfil/password/', admin_perfil_cambiar_password, name='api-admin-perfil-password'),
    path('api/admin/perfil/foto/', admin_perfil_foto, name='api-admin-perfil-foto'),
    path('api/admin/multimedia/', multimedia_list, name='api-admin-multimedia-list'),
    path('api/admin/multimedia/upload/', multimedia_upload, name='api-admin-multimedia-upload'),
    path('api/admin/multimedia/reorder/', multimedia_reorder, name='api-admin-multimedia-reorder'),
    path('api/admin/multimedia/<int:multimedia_id>/principal/', multimedia_set_principal, name='api-admin-multimedia-principal'),
    path('api/admin/multimedia/<int:multimedia_id>/', multimedia_delete, name='api-admin-multimedia-delete'),
    path('api/rutas/', rutas_list, name='api-rutas'),
    path('api/rutas/<int:ruta_id>/', rutas_detail, name='api-rutas-detail'),
    path('api/emprendimientos/', emprendimientos_list, name='api-emprendimientos'),
    path('api/emprendimientos/<int:emp_id>/', emprendimientos_detail, name='api-emprendimientos-detail'),
    path('api/usuarios/', usuarios_list, name='api-usuarios'),
    path('api/eventos/', eventos_list, name='api-eventos'),
    path('api/eventos/<int:evento_id>/', eventos_detail, name='api-eventos-detail'),
    path('api/resenas/', resenas_list, name='api-resenas-list'),
    path('api/resenas/crear/', resenas_create, name='api-resenas-create'),
    path('api/resenas/<int:resena_id>/', resenas_update, name='api-resenas-update'),
    path('api/admin/eventos/<int:evento_id>/detalle/', admin_evento_detail, name='api-admin-evento-detail'),
    path('api/publicaciones/', publicaciones_list, name='api-publicaciones'),
    path('api/reportes/', reportes_list, name='api-reportes'),
    path('api/auditorias/', auditorias_list, name='api-auditorias'),
    path('api/dashboard/', dashboard_summary, name='api-dashboard-summary'),
    path('api/configuracion/', configuracion_list, name='api-configuracion'),
    path('api/admin/errores/', admin_errores_list, name='api-admin-errores-list'),
    path('api/admin/errores/reportar/', admin_errores_reportar_cliente, name='api-admin-errores-reportar'),
    path('api/admin/errores/<int:error_id>/estado/', admin_errores_cambiar_estado, name='api-admin-errores-estado'),
    path('api/admin/papelera/', admin_papelera_list, name='api-admin-papelera-list'),
    path('api/admin/papelera/<str:tipo>/<int:item_id>/restaurar/', admin_papelera_restaurar, name='api-admin-papelera-restaurar'),
    path('api/admin/papelera/<str:tipo>/<int:item_id>/permanente/', admin_papelera_eliminar_permanente, name='api-admin-papelera-permanente'),
    path('api/admin/resenas/', admin_resenas_list, name='api-admin-resenas-list'),
    path('api/admin/resenas/<int:resena_id>/activo/', admin_resenas_cambiar_activo, name='api-admin-resenas-activo'),
    path('api/auth/register/', register, name='api-auth-register'),
    path('api/auth/login/', login, name='api-auth-login'),
    path('api/auth/password-reset/', password_reset_request, name='api-auth-password-reset'),
    path('api/auth/password-reset/confirm/', password_reset_confirm, name='api-auth-password-reset-confirm'),
]
