# Generated by Django 5.2.6 on 2026-07-05 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errores', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_tipo_ec1c97_idx',
            old_name='error_logs_tipo_es_8c2f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_modulo_a870fe_idx',
            old_name='error_logs_modulo__a1b2c3_idx',
        ),
    ]
