# Generated by Django 6.0.5 on 2026-05-28 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaEstadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('visitas', models.IntegerField(default=0)),
                ('origen', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Consulta Estadística',
                'db_table': 'consultas_estadisticas',
                'indexes': [models.Index(fields=['entidad_tipo', 'entidad_id', 'fecha'], name='consultas_e_entidad_78f542_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(blank=True, max_length=100, null=True)),
                ('formato', models.CharField(blank=True, max_length=20, null=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('archivo_generado', models.CharField(blank=True, max_length=255, null=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'db_table': 'reportes_generados',
                'ordering': ['-generado_en'],
            },
        ),
    ]
