# Generated by Django 6.0.5 on 2026-05-28 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('sitio_web', models.URLField(blank=True, max_length=255, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('canton', models.CharField(blank=True, max_length=100, null=True)),
                ('parroquia', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('historia', models.TextField(blank=True, null=True)),
                ('mision', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('logo_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_secundario', models.CharField(blank=True, max_length=255, null=True)),
                ('favicon', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_logo', models.BooleanField(default=True)),
                ('mostrar_menu', models.BooleanField(default=True)),
                ('mostrar_buscador', models.BooleanField(default=True)),
                ('mostrar_redes', models.BooleanField(default=True)),
                ('texto_superior', models.CharField(blank=True, max_length=255, null=True)),
                ('color_fondo', models.CharField(blank=True, max_length=20, null=True)),
                ('color_texto', models.CharField(blank=True, max_length=20, null=True)),
                ('altura_header', models.IntegerField(default=80)),
                ('sticky', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Header',
                'db_table': 'configuracion_header',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('mostrar_redes', models.BooleanField(default=True)),
                ('mostrar_contacto', models.BooleanField(default=True)),
                ('mostrar_mapa', models.BooleanField(default=True)),
                ('copyright_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('color_fondo', models.CharField(blank=True, max_length=20, null=True)),
                ('color_texto', models.CharField(blank=True, max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footers', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Footer',
                'db_table': 'configuracion_footer',
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=150, unique=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Configuración',
                'db_table': 'configuraciones',
            },
        ),
        migrations.CreateModel(
            name='AparienciaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primario', models.CharField(blank=True, max_length=20, null=True)),
                ('color_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('color_terciario', models.CharField(blank=True, max_length=20, null=True)),
                ('fuente_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('fuente_secundaria', models.CharField(blank=True, max_length=100, null=True)),
                ('tamano_fuente_base', models.IntegerField(default=16)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('borde_radio', models.IntegerField(default=10)),
                ('sombra_global', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apariencia', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Apariencia del Sistema',
                'db_table': 'apariencia_sistema',
            },
        ),
        migrations.CreateModel(
            name='MenuNavegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruta', models.CharField(blank=True, max_length=255, null=True)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('tipo_enlace', models.CharField(blank=True, max_length=50, null=True)),
                ('abierto_nueva_pestana', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='empresa.empresa')),
                ('menu_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='empresa.menunavegacion')),
            ],
            options={
                'verbose_name': 'Menú de Navegación',
                'db_table': 'menu_navegacion',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Red Social',
                'db_table': 'redes_sociales',
            },
        ),
    ]
