# Generated by Django 6.0.5 on 2026-05-28 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('altitud', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('horario', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('visitas', models.IntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atractivos', to='catalogos.categoria')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atractivos_creados', to=settings.AUTH_USER_MODEL)),
                ('estado_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atractivos', to='catalogos.estadopublicacion')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atractivos', to='catalogos.parroquia')),
            ],
            options={
                'verbose_name': 'Atractivo Turístico',
                'db_table': 'atractivos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AtractivoAccesibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_via', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_via', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_transporte', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo_desplazamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('distancia_referencial_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('posee_senalizacion', models.BooleanField(null=True)),
                ('acceso_discapacidad', models.BooleanField(null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('atractivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accesibilidad', to='atractivos.atractivo')),
            ],
            options={
                'verbose_name': 'Accesibilidad de Atractivo',
                'db_table': 'atractivo_accesibilidad',
            },
        ),
        migrations.CreateModel(
            name='AtractivoAdministracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_administrador', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_administrador', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('atractivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administracion', to='atractivos.atractivo')),
            ],
            options={
                'verbose_name': 'Administración de Atractivo',
                'db_table': 'atractivo_administracion',
            },
        ),
        migrations.CreateModel(
            name='AtractivoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clima', models.CharField(blank=True, max_length=100, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=50, null=True)),
                ('precipitacion', models.CharField(blank=True, max_length=50, null=True)),
                ('linea_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('escenario', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_ingreso', models.CharField(blank=True, max_length=100, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horario', models.CharField(blank=True, max_length=255, null=True)),
                ('formas_pago', models.TextField(blank=True, null=True)),
                ('meses_recomendados', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('atractivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='atractivos.atractivo')),
            ],
            options={
                'verbose_name': 'Detalle de Atractivo',
                'db_table': 'atractivo_detalles',
            },
        ),
        migrations.CreateModel(
            name='AtractivoEstadoConservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_conservacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_seguridad', models.CharField(blank=True, max_length=100, null=True)),
                ('posee_senal_internet', models.BooleanField(null=True)),
                ('cobertura_operadora', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_salud_cercano', models.CharField(blank=True, max_length=255, null=True)),
                ('distancia_centro_salud_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('atractivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_conservacion', to='atractivos.atractivo')),
            ],
            options={
                'verbose_name': 'Estado de Conservación',
                'db_table': 'atractivo_estado_conservacion',
            },
        ),
        migrations.CreateModel(
            name='AtractivoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atractivo_actividades', to='catalogos.actividad')),
                ('atractivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atractivo_actividades', to='atractivos.atractivo')),
            ],
            options={
                'verbose_name': 'Actividad del Atractivo',
                'db_table': 'atractivo_actividades',
                'unique_together': {('atractivo', 'actividad')},
            },
        ),
        migrations.CreateModel(
            name='AtractivoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('atractivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atractivo_servicios', to='atractivos.atractivo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atractivo_servicios', to='catalogos.servicio')),
            ],
            options={
                'verbose_name': 'Servicio del Atractivo',
                'db_table': 'atractivo_servicios',
                'unique_together': {('atractivo', 'servicio')},
            },
        ),
    ]
