# Generated by Django 6.0.5 on 2026-05-28 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atractivos', '__first__'),
        ('catalogos', '__first__'),
        ('rutas', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('altitud', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('visitas', models.IntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprendimientos', to='catalogos.categoria')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprendimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('estado_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprendimientos', to='catalogos.estadopublicacion')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprendimientos', to='catalogos.parroquia')),
            ],
            options={
                'verbose_name': 'Emprendimiento',
                'verbose_name_plural': 'Emprendimientos',
                'db_table': 'emprendimientos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EmprendimientoHistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=100)),
                ('estado_nuevo', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='emprendimientos.emprendimiento')),
            ],
            options={
                'db_table': 'emprendimiento_historial_estados',
            },
        ),
        migrations.CreateModel(
            name='EmprendimientoRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_red', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='emprendimientos.emprendimiento')),
            ],
            options={
                'verbose_name': 'Red Social de Emprendimiento',
                'db_table': 'emprendimiento_redes_sociales',
            },
        ),
        migrations.CreateModel(
            name='EmprendimientoRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('distancia_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('atractivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atractivos.atractivo')),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='emprendimientos.emprendimiento')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta')),
            ],
            options={
                'db_table': 'emprendimiento_relaciones',
            },
        ),
        migrations.CreateModel(
            name='EmprendimientoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='emprendimientos.emprendimiento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.servicio')),
            ],
            options={
                'db_table': 'emprendimiento_servicios',
                'unique_together': {('emprendimiento', 'servicio')},
            },
        ),
    ]
