# Generated by Django 6.0.5 on 2026-05-28 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cambiado_en', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_publicaciones', to=settings.AUTH_USER_MODEL)),
                ('estado_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_anterior', to='catalogos.estadopublicacion')),
                ('estado_nuevo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_nuevo', to='catalogos.estadopublicacion')),
            ],
            options={
                'verbose_name': 'Historial de Publicación',
                'db_table': 'historial_publicacion',
                'ordering': ['-cambiado_en'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('accion', models.CharField(blank=True, choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('PUBLICAR', 'Publicar'), ('CONFIGURAR', 'Configurar')], max_length=50, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'db_table': 'auditorias',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tabla_afectada', 'entidad_id'], name='auditorias_tabla_a_b756ae_idx'), models.Index(fields=['usuario', 'fecha'], name='auditorias_usuario_e97720_idx')],
            },
        ),
    ]
