# Generated by Django 6.0.5 on 2026-05-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_tipo', models.CharField(blank=True, choices=[('atractivo', 'Atractivo'), ('ruta', 'Ruta'), ('emprendimiento', 'Emprendimiento'), ('evento', 'Evento'), ('empresa', 'Empresa')], max_length=50, null=True)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('imagen', 'Imagen'), ('video', 'Video'), ('documento', 'Documento')], max_length=50, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Multimedia',
                'db_table': 'multimedia',
                'ordering': ['orden'],
                'indexes': [models.Index(fields=['entidad_tipo', 'entidad_id'], name='multimedia_entidad_cb1a93_idx')],
            },
        ),
    ]
